version: '3.3'
services:
  react_builder:
    image: node:17.2.0-stretch
    ports:
      - "3000:3000"
    expose:
      - 3000
    working_dir: /app
    volumes:
      - './sample:/app'
      - './entrypoint.sh:/entrypoint.sh'
    command: start
    # build production
    entrypoint: /entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true

  web-cdn:
    image: 'nginx:1.21.6-alpine'
    volumes:
      # - ./web-cdn/nginx.conf:/etc/nginx/nginx.conf
      - ./web-cdn/default_site.conf:/etc/nginx/conf.d/default.conf
      - ./sample/build/:/usr/share/nginx/html
    ports:
      - 3500:80
    user: root
